<?php if($datereader == false){ die('شما مجوز دسترسی به این صفحه را ندارید.'); } ?>
<h3 class="sub-header">دریافت تراکنش ها برای همه پذیرنده ها</h3>
<?php
### GENERATED BY POOYA SABRAMOOZ IN 4/28/2014 ###
################################################################
#FETCHING INFORMATION
error_reporting(E_ALL);
ini_set('display_errors','1');
###connect to db
$connection = mysqli_connect('localhost','sunnycart','kosenanat:dD1369','sunnycart') OR die('FAILED...');
mysqli_set_charset($connection, 'utf8');
#####   FUNCTION   ######
function insertToDb($inputName,$inputValue,$id,$connection){
				mysqli_query($connection,"UPDATE transaction SET $inputName='$inputValue' WHERE id='$id'");				
			}
###########
$envelope = '';
$curlUsername = 'sgsj14';
$curlPassword = '57091096';
########
date_default_timezone_set('Asia/Tehran');
//$FromDate = date('Ymd');
$FromDate = date('Ymd',mktime(0, 0, 0, date('m')  , date('d')-1, date('Y')));
$ToDate = date('Ymd');
#######

if(isset($_POST['getTransactionByDatefull'])){

$terminal_id_query="SELECT terminal_id,activate FROM receptors WHERE terminal_id > 1 AND activate = '1' ORDER BY RAND() ";
		$terminal_id_result=mysqli_query($connection,$terminal_id_query);
		while($terminal_id = mysqli_fetch_assoc($terminal_id_result)){
			$curlTerminalId = $terminal_id['terminal_id'];
					


	$FromDate = $_POST['FromDate'];
	$ToDate = $_POST['ToDate'];
$envelope = '<soap:Envelope xmlns:bpm="http://bpmellat.co/" xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Header>
      <wsse:Security soap:mustUnderstand="true" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <wsu:Timestamp wsu:Id="Timestamp-8" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsu:Created>'.date('Y-m-d').'T16:02:38.053Z</wsu:Created>
            <wsu:Expires>'.date('Y-m-d').'T16:03:38.053Z</wsu:Expires>
         </wsu:Timestamp>
         <wsse:UsernameToken wsu:Id="UsernameToken-7" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsse:Username>'.$curlUsername.'</wsse:Username>
            <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">'.$curlPassword.'</wsse:Password>
            <wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">D5L5sjDemfkf/bq5zn7DMA==</wsse:Nonce>
            <wsu:Created>'.date('Y-m-d').'T16:02:34.714Z</wsu:Created>
         </wsse:UsernameToken>
      </wsse:Security>
   </soap:Header>
   <soap:Body>
      <bpm:getTransactionByDate>
         <bpm:TerminalId>'.$curlTerminalId.'</bpm:TerminalId>
         <bpm:FromDate>'.$FromDate.'</bpm:FromDate>
         <bpm:ToDate>'.$ToDate.'</bpm:ToDate>
      </bpm:getTransactionByDate>
   </soap:Body>
</soap:Envelope>';

	
if(!empty($envelope)){
$soap_do = curl_init();
curl_setopt($soap_do, CURLOPT_URL, "http://bos.bpm.bankmellat.ir/backoffice/Services/bpm/TransactionService.asmx?wsdl" );
curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 0);
curl_setopt($soap_do, CURLOPT_TIMEOUT,        400);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true );
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($soap_do, CURLOPT_POST,           true );            
curl_setopt($soap_do, CURLOPT_POSTFIELDS,     $envelope); 
curl_setopt($soap_do, CURLOPT_VERBOSE, TRUE); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, array("Content-Type: text/xml","SOAPAction: \"/soap/action/query\"", "Content-length: ".strlen($envelope))); 

$result = curl_exec($soap_do);
//print_r($result);
echo '<hr>';

$fp = fopen('data.xml', 'w');
$result = str_replace('&lt;','<',$result);
$result = str_replace('&gt;','>',$result);
$result = str_replace(' &#xd;','',$result);
$result = str_replace('><',">\n<",$result);
$result = str_replace('<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">',"",$result);
$result = str_replace('<soap:Body>',"",$result);
####
$result = str_replace('<getTransactionByDateResponse xmlns="http://bpmellat.co/">',"",$result);
$result = str_replace('<getTransactionByDateResult>',"",$result);
$result = str_replace('</getTransactionByDateResult>',"",$result);
$result = str_replace('</getTransactionByDateResponse>',"",$result);
####
$result = str_replace('</soap:Body>',"",$result);
$result = str_replace('</soap:Envelope>',"",$result);
$result=trim($result);


fwrite($fp, $result);
################
###############################################################

						
		### PARSE XML
		$url='data.xml';
		$xml = simplexml_load_file($url);
		//$xml = simplexml_load_string($result);
			$query=$xml->xpath(' //response/record/field ');
foreach($query as $test => $obj){

		### DISPLAY ERROR No.					
		if($obj['name']=='responseCode' && $obj['value']!='000'){ echo "ERROR No. <strong style='color:red;'>".$obj['value']."</strong><br>";}
		
		### INSERT NEW ID 			
			if($obj['name']=='Id'){
				//echo $obj['value'],'<br>';
				$id=$obj['value'];
				mysqli_query($connection,"INSERT INTO transaction(id) VALUES('$id')");
				echo "<strong style='color:red;'>",mysqli_error($connection),"</strong><br>";
				}
		### UPDATE ROWS BY ID
			if($obj['name']=='customerId'){
				//echo $obj['value'],'<br>';	
				$customerId=$obj['value'];
				$inputName='customerId';
				insertToDb($inputName,$customerId,$id,$connection);	
				}
			if($obj['name']=='accountNumber'){
				//echo $obj['value'],'<br>';
				$accountNumber=$obj['value'];
				$inputName='accountNumber';
				insertToDb($inputName,$accountNumber,$id,$connection);				
				}
			if($obj['name']=='terminalId'){
				echo $obj['value'],'<br>';	
				$terminalId=$obj['value'];
				$inputName='terminalId';
				insertToDb($inputName,$terminalId,$id,$connection);	
				}
			if($obj['name']=='channelType'){
				//echo $obj['value'],'<br>';
				$channelType=$obj['value'];
				$inputName='channelType';
				insertToDb($inputName,$channelType,$id,$connection);				
				}
			if($obj['name']=='internalReferenceId'){
				//echo $obj['value'],'<br>';	
				$internalReferenceId=$obj['value'];
				$inputName='internalReferenceId';
				insertToDb($inputName,$internalReferenceId,$id,$connection);	
				}
			if($obj['name']=='transactionType'){
				//echo $obj['value'],'<br>';
				$transactionType=$obj['value'];
				$inputName='transactionType';
				insertToDb($inputName,$transactionType,$id,$connection);				
				}
			if($obj['name']=='transactionDate'){
				//echo $obj['value'],'<br>';	
				$transactionDate=$obj['value'];
				$inputName='transactionDate';
				insertToDb($inputName,$transactionDate,$id,$connection);	
				}
			if($obj['name']=='transactionTime'){
				//echo $obj['value'],'<br>';
				$transactionTime=$obj['value'];
				$inputName='transactionTime';
				insertToDb($inputName,$transactionTime,$id,$connection);				
				}
			if($obj['name']=='amount'){
				//echo $obj['value'],'<br>';	
				$amount=$obj['value'];
				$inputName='amount';
				insertToDb($inputName,$amount,$id,$connection);	
				}
			if($obj['name']=='pan'){
				//echo $obj['value'],'<br>';
				$pan=$obj['value'];
				$inputName='pan';
				insertToDb($inputName,$pan,$id,$connection);				
				}
			if($obj['name']=='payerId'){
				//echo $obj['value'],'<br>';	
				$payerId=$obj['value'];
				$inputName='payerId';
				insertToDb($inputName,$payerId,$id,$connection);	
				}
			if($obj['name']=='billId'){
				//echo $obj['value'],'<br>';
				$billId=$obj['value'];
				$inputName='billId';
				insertToDb($inputName,$billId,$id,$connection);				
				}
			if($obj['name']=='paymentId'){
				//echo $obj['value'],'<br>';	
				$paymentId=$obj['value'];
				$inputName='paymentId';
				insertToDb($inputName,$paymentId,$id,$connection);	
				}
			if($obj['name']=='saleOrderId'){
				//echo $obj['value'],'<br>';
				$saleOrderId=$obj['value'];
				$inputName='saleOrderId';
				insertToDb($inputName,$saleOrderId,$id,$connection);				
				}
			if($obj['name']=='additionalData'){
				//echo $obj['value'],'<br>';	
				$additionalData=$obj['value'];
				$inputName='additionalData';
				insertToDb($inputName,$additionalData,$id,$connection);	
				}
			if($obj['name']=='settlementDate'){
				//echo $obj['value'],'<br>';
				$settlementDate=$obj['value'];
				$inputName='settlementDate';
				insertToDb($inputName,$settlementDate,$id,$connection);				
				}
			if($obj['name']=='settlementTime'){
				//echo $obj['value'],'<br>';	
				$settlementTime=$obj['value'];
				$inputName='settlementTime';
				insertToDb($inputName,$settlementTime,$id,$connection);	
			}

}echo "<strong style='color:green;'>------------------ Total Records Submitted Successfully ------------------</strong>";	
}

}
}
?>
<?php
if(isset($_POST['min_database1'])){
	
	$min_database1_query="DELETE FROM `transaction` WHERE payerId=0";
	mysqli_query($connection,$min_database1_query);
		
	}
elseif(isset($_POST['min_database2'])){
		
	$min_database2_query="DELETE FROM `transaction` WHERE accountNumber<>4975553214";
	mysqli_query($connection,$min_database2_query);		
		
}elseif(isset($_POST['database_5'])){
		
	//$database_payerId_to_1_query="UPDATE `transaction` SET `payerId`='1'";
	//	mysqli_query($connection,$database_payerId_to_1_query);	
	$fetch_temp_query = "SELECT * FROM temp;";
	$fetch_temp_result = mysqli_query($connection,$fetch_temp_query);
	$fetch_temp_row = mysqli_fetch_assoc($fetch_temp_result);
	
	//$FromId = '100093995889';
	$FromId = $fetch_temp_row['temp_id'];
	### first_card ####		
				function card_number($cart_pri,$connection){	
					if(!empty($cart_pri)){
							$check_cart_pri_query="SELECT id,cart_pri,cart_sec,cart_ter,payerId FROM users WHERE cart_pri='$cart_pri' OR cart_sec='$cart_pri' OR cart_ter='$cart_pri'";
							$check_cart_pri_result=mysqli_query($connection , $check_cart_pri_query);
							$check_cart_pri_rows = mysqli_fetch_assoc($check_cart_pri_result);
							$check_cart_pri_num_rows = mysqli_num_rows($check_cart_pri_result);
								if($check_cart_pri_num_rows==0 || $check_cart_pri_num_rows==1){
									return 1;
									}else{
										return $check_cart_pri_num_rows+1;
										}		
								//return $check_cart_pri_num_rows+1;	
							$check_cart_pri_result->close();
							}
				}
		
	$database_5_query = "SELECT id,payerId,pan FROM transaction  WHERE id > '$FromId'; ";
	$database_5_result = mysqli_query($connection,$database_5_query);
	while($database_5_row = mysqli_fetch_assoc($database_5_result)){
		if($database_5_row['payerId']==5){
			echo $database_5_row['pan'].'-';
			$id_5 = $database_5_row['id'];
			#####
			
			$payerId_5 = card_number($database_5_row['pan'],$connection);
			$database_update_query = "UPDATE transaction SET payerId='$payerId_5' WHERE id='$id_5'";
			mysqli_query($connection,$database_update_query);
			#####
			//echo $database_5_row['id'];
			}
		}	
}
/*elseif(isset($_POST['database_payerId_to_1'])){
		
	$database_payerId_to_1_query="UPDATE `transaction` SET `payerId`='1'";
	mysqli_query($connection,$database_payerId_to_1_query);		
		
}*/
?>
<form method="post" role="form" class="form-inline">
<label>از تاریخ : </label><input type="text" name="FromDate" class="form-control"  value="<?php echo $FromDate; ?>">
<label>تا تاریخ : </label><input type="text" name="ToDate" class="form-control"  value="<?php echo $ToDate; ?>">
<input type="submit" name="getTransactionByDatefull"  value="دریافت اطلاعات" class="btn btn-sm btn-success form-control">
</form>
<br><hr color="#FF0000" size="1"><br>
<form method="post" role="form" class="form-inline">
	<input type="submit" disabled value="مرحله اول تنظیم دیتابیس" name="min_database1" class="form-control btn btn-md btn-warning">
    <input type="submit" value="مرحله دوم تنظیم دیتابیس" name="min_database2" class="form-control btn btn-md btn-primary">
    <input type="submit" value="شناسه 5 ها مدیریت شود" name="database_5" class="form-control btn btn-md btn-success">
    <!--<input type="submit" value="شناسه واریز ها 1 شود" name="database_payerId_to_1" class="form-control btn btn-md btn-success">-->
</form>