<?php if($mail_group_send == false){ die('شما مجوز دسترسی به این صفحه را ندارید.'); } ?>
<h3 class="sub-header">ارسال ایمیل تکی و گروهی</h3>
<?php
### GENERATED BY POOYA SABRAMOOZ ###
	error_reporting(E_ALL);
	ini_set('display_errors','1');
	include('jdf.php');
	date_default_timezone_set('Asia/Tehran');
	$error ='';

### connect to db ###

	$connection = mysqli_connect('localhost','sunnycart','kosenanat:dD1369','sunnycart') OR die('FAILED...');
	mysqli_set_charset($connection, 'utf8');
	
#####################
	if(isset($_POST['groupSendMail'])){
	
		$fetch_users_query = "SELECT mail,first_name,last_name,gender FROM users WHERE melli_code='0012432385';";
		$fetch_users_result = mysqli_query($connection,$fetch_users_query);
	
		while($fetch_users_row = mysqli_fetch_assoc($fetch_users_result)){
				$mail = $fetch_users_row['mail'];
				$first_name = $fetch_users_row['first_name'];
				$last_name = $fetch_users_row['last_name'];
				$gender = $fetch_users_row['gender'];
				$text = $_POST['text'];
				$subject = $_POST['subject'];		
									if(isset($gender)){
											if($gender=='مرد'){$smsgender='آقای';}elseif($gender=='زن'){$smsgender='خانم';}
										
										//send welcome E-Mail
							$to=$mail;
							$message="
								<html>
									<head><title></title></head>
									<body style='color:#999;' bgcolor='#666666'>
										<h3>سلام $smsgender $first_name $last_name</h3>										
											$text;
									</body>
								</html>
							";
							$header="content-type:text/html;charset=utf-8";
							$header.="sunny cart <info@scards.ir>";
							mail($to,$subject,$message,$header);
									}
		}
									$error = '
											<div class="col-lg-12 col-md-6">
												<br style="margin:20px 0;">
												<div class="alert alert-success alert-dismissable">
												  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
												  ایمیل گروهی مورد نظر ارسال شد.
												</div>
											</div>
										';

	}elseif(isset($_POST['SendMail'])){
				$to = $_POST['to'];
				$message = $_POST['text'];
				$subject = $_POST['subject'];

							$header="content-type:text/html;charset=utf-8";
							$header.="sunny cart <info@scards.ir>";
							mail($to,$subject,$message,$header);
								$error = '
											<div class="col-lg-12 col-md-6">
												<br style="margin:20px 0;">
												<div class="alert alert-success alert-dismissable">
												  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
												  ایمیل مورد نظر ارسال شد.
												</div>
											</div>
										';
	}
?>
<div class="col-lg-6 col-md-6">
    <form method="post" role="form" class="form">
    	<input type="text" class="form-control" name="subject" placeholder="موضوع ایمیل را وارد نمایید"><br>
        <textarea name="text" class="form-control" rows="6"></textarea><br>
        <input type="submit" name="groupSendMail" value="ارسال به تمامی سهامداران" class="form-control btn btn-md btn-danger" onClick="return myfunction();">
    </form>
</div>
<div class="col-lg-6 col-md-6">
    <form method="post" role="form" class="form">
    	<input type="text" class="form-control" name="to" placeholder="ایمیل شخص مورد نظر را وارد نمایید"><br>
        <input type="text" class="form-control" name="subject" placeholder="موضوع ایمیل را وارد نمایید"><br>
        <textarea name="text" class="form-control" rows="3" style="height:97px;"></textarea><br>
        <input type="submit" name="SendMail" value="ارسال" class="form-control btn btn-md btn-success">
    </form>
</div>

<?php echo $error; ?>

<script>
   function myfunction(){
    		var password = prompt("لطفا رمز ارسال ایمیل گروهی را وارد کنید");

			if (password!=null && password=='1234568') {
				return true;
			}return false;
}
</script>