<?php if($reader == false){ die('شما مجوز دسترسی به این صفحه را ندارید.'); } ?>
<h3 class="sub-header">دریافت تراکنش ها به تفکیک پذیرنده ها</h3>
<?php
### GENERATED BY POOYA SABRAMOOZ IN 4/28/2014 ###
################################################################
#FETCHING INFORMATION
error_reporting(E_ALL);
ini_set('display_errors','1');

###connect to db
		$connection = mysqli_connect('localhost','sunnycart','kosenanat:dD1369','sunnycart') OR die('FAILED...');
		mysqli_set_charset($connection, 'utf8');
###########
include('getTransactions.php');
if(!empty($envelope)){
$soap_do = curl_init();
curl_setopt($soap_do, CURLOPT_URL, "http://bos.bpm.bankmellat.ir/backoffice/Services/bpm/TransactionService.asmx?wsdl" );
curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 0);
curl_setopt($soap_do, CURLOPT_TIMEOUT,        400);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true );
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($soap_do, CURLOPT_POST,           true );            
curl_setopt($soap_do, CURLOPT_POSTFIELDS,     $envelope); 
curl_setopt($soap_do, CURLOPT_VERBOSE, TRUE); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, array("Content-Type: text/xml","SOAPAction: \"/soap/action/query\"", "Content-length: ".strlen($envelope))); 

$result = curl_exec($soap_do);
print_r($result);
echo '<hr>';

$fp = fopen('data.xml', 'w');
$result = str_replace('&lt;','<',$result);
$result = str_replace('&gt;','>',$result);
$result = str_replace(' &#xd;','',$result);
$result = str_replace('><',">\n<",$result);
$result = str_replace('<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">',"",$result);
$result = str_replace('<soap:Body>',"",$result);
####
$result = str_replace('<getTransactionByDateResponse xmlns="http://bpmellat.co/">',"",$result);
$result = str_replace('<getTransactionByDateResult>',"",$result);
$result = str_replace('</getTransactionByDateResult>',"",$result);
$result = str_replace('</getTransactionByDateResponse>',"",$result);
####
$result = str_replace('<getTransactionByIdResponse xmlns="http://bpmellat.co/">',"",$result);
$result = str_replace('<getTransactionByIdResult>',"",$result);
$result = str_replace('</getTransactionByIdResult>',"",$result);
$result = str_replace('</getTransactionByIdResponse>',"",$result);
####
$result = str_replace('<getTransactionByCustomerIdResponse xmlns="http://bpmellat.co/">',"",$result);
$result = str_replace('<getTransactionByCustomerIdResult>',"",$result);
$result = str_replace('</getTransactionByCustomerIdResult>',"",$result);
$result = str_replace('</getTransactionByCustomerIdResponse>',"",$result);
####
$result = str_replace('</soap:Body>',"",$result);
$result = str_replace('</soap:Envelope>',"",$result);
$result=trim($result);


fwrite($fp, $result);
################
###############################################################
function insertToDb($inputName,$inputValue,$id,$connection){
				mysqli_query($connection,"UPDATE transaction SET $inputName='$inputValue' WHERE id='$id'");				
			}
					
		
		
		### PARSE XML
		$url='data.xml';
		$xml = simplexml_load_file($url);
		//$xml = simplexml_load_string($result);
			$query=$xml->xpath(' //response/record/field ');
foreach($query as $test => $obj){

		### DISPLAY ERROR No.					
		if($obj['name']=='responseCode' && $obj['value']!='000'){ die("ERROR No. <strong style='color:red;'>".$obj['value']."</strong><br>");}
		
		### INSERT NEW ID 			
			if($obj['name']=='Id'){
				echo $obj['value'],'<br>';
				$id=$obj['value'];
				mysqli_query($connection,"INSERT INTO transaction(id) VALUES('$id')");
				echo "<strong style='color:red;'>",mysqli_error($connection),"</strong><br>";
				}
		### UPDATE ROWS BY ID
			if($obj['name']=='customerId'){
				echo $obj['value'],'<br>';	
				$customerId=$obj['value'];
				$inputName='customerId';
				insertToDb($inputName,$customerId,$id,$connection);	
				}
			if($obj['name']=='accountNumber'){
				echo $obj['value'],'<br>';
				$accountNumber=$obj['value'];
				$inputName='accountNumber';
				insertToDb($inputName,$accountNumber,$id,$connection);				
				}
			if($obj['name']=='terminalId'){
				echo $obj['value'],'<br>';	
				$terminalId=$obj['value'];
				$inputName='terminalId';
				insertToDb($inputName,$terminalId,$id,$connection);	
				}
			if($obj['name']=='channelType'){
				echo $obj['value'],'<br>';
				$channelType=$obj['value'];
				$inputName='channelType';
				insertToDb($inputName,$channelType,$id,$connection);				
				}
			if($obj['name']=='internalReferenceId'){
				echo $obj['value'],'<br>';	
				$internalReferenceId=$obj['value'];
				$inputName='internalReferenceId';
				insertToDb($inputName,$internalReferenceId,$id,$connection);	
				}
			if($obj['name']=='transactionType'){
				echo $obj['value'],'<br>';
				$transactionType=$obj['value'];
				$inputName='transactionType';
				insertToDb($inputName,$transactionType,$id,$connection);				
				}
			if($obj['name']=='transactionDate'){
				echo $obj['value'],'<br>';	
				$transactionDate=$obj['value'];
				$inputName='transactionDate';
				insertToDb($inputName,$transactionDate,$id,$connection);	
				}
			if($obj['name']=='transactionTime'){
				echo $obj['value'],'<br>';
				$transactionTime=$obj['value'];
				$inputName='transactionTime';
				insertToDb($inputName,$transactionTime,$id,$connection);				
				}
			if($obj['name']=='amount'){
				echo $obj['value'],'<br>';	
				$amount=$obj['value'];
				$inputName='amount';
				insertToDb($inputName,$amount,$id,$connection);	
				}
			if($obj['name']=='pan'){
				echo $obj['value'],'<br>';
				$pan=$obj['value'];
				$inputName='pan';
				insertToDb($inputName,$pan,$id,$connection);				
				}
			if($obj['name']=='payerId'){
				echo $obj['value'],'<br>';	
				$payerId=$obj['value'];
				$inputName='payerId';
				insertToDb($inputName,$payerId,$id,$connection);	
				}
			if($obj['name']=='billId'){
				echo $obj['value'],'<br>';
				$billId=$obj['value'];
				$inputName='billId';
				insertToDb($inputName,$billId,$id,$connection);				
				}
			if($obj['name']=='paymentId'){
				echo $obj['value'],'<br>';	
				$paymentId=$obj['value'];
				$inputName='paymentId';
				insertToDb($inputName,$paymentId,$id,$connection);	
				}
			if($obj['name']=='saleOrderId'){
				echo $obj['value'],'<br>';
				$saleOrderId=$obj['value'];
				$inputName='saleOrderId';
				insertToDb($inputName,$saleOrderId,$id,$connection);				
				}
			if($obj['name']=='additionalData'){
				echo $obj['value'],'<br>';	
				$additionalData=$obj['value'];
				$inputName='additionalData';
				insertToDb($inputName,$additionalData,$id,$connection);	
				}
			if($obj['name']=='settlementDate'){
				echo $obj['value'],'<br>';
				$settlementDate=$obj['value'];
				$inputName='settlementDate';
				insertToDb($inputName,$settlementDate,$id,$connection);				
				}
			if($obj['name']=='settlementTime'){
				echo $obj['value'],'<br>';	
				$settlementTime=$obj['value'];
				$inputName='settlementTime';
				insertToDb($inputName,$settlementTime,$id,$connection);	
			}

}echo "<strong style='color:green;'>------------------ Total Records Submitted Successfully ------------------</strong>";	
}
?>