<?php if($sms_management == false){ die('شما مجوز دسترسی به این صفحه را ندارید.'); } ?>
<h3 class="sub-header">مدیریت اس ام اس ها</h3>
<div class="col-lg-12 col-md-12">
<?php
### GENERATED BY POOYA SABRAMOOZ ###
	error_reporting(E_ALL);
	//ob_start();
	ini_set('display_errors','1');
	//ini_set('output_buffering','4096');
	
	include('jdf.php');
	date_default_timezone_set('Asia/Tehran');
	
### connect to db ###

	$connection = mysqli_connect('localhost','sunnycart','kosenanat:dD1369','sunnycart') OR die('FAILED...');
	mysqli_set_charset($connection, 'utf8');
			
####### SMS FUNCTION #########

	function pooya_sms($pooya_to,$pooya_message,$connection){
		ini_set("soap.wsdl_cache_enabled", "0");
		$sms_client = new SoapClient('http://87.107.121.54/post/send.asmx?wsdl', array('encoding'=>'UTF-8'));
		
		$parameters['username'] = "9124077897";
		$parameters['password'] = "3755";
		$parameters['to'] = $pooya_to;
		$parameters['from'] = "2188806627";
		$parameters['text'] =$pooya_message;
		$parameters['isflash'] =false;
		
		$recId = $sms_client->SendSimpleSMS2($parameters)->SendSimpleSMS2Result;
		$date=time();
		
		$mysqli = $connection;
		//$send_sms_query="INSERT INTO sms(`id`, `mobile`, `text`, `recId`, `date`) VALUES ('','$pooya_to','$pooya_message','$recId','$date')";
		//$send_sms_result=$mysqli->query($send_sms_query);
		$send_sms_query = "INSERT INTO sms(`id`, `mobile`, `text`, `recId`, `date`) VALUES ('','$pooya_to','$pooya_message','$recId','$date')";
		$send_sms_result = mysqli_query($connection,$send_sms_query);
		return $recId;
		}
	
	function pooya_delivery($recId){
		ini_set("soap.wsdl_cache_enabled", "0");
		$delivery_client = new SoapClient('http://87.107.121.54/post/send.asmx?wsdl', array('encoding'=>'UTF-8'));		
		$parameters['recId'] = $recId;
		$delivery_status = $delivery_client->GetDelivery($parameters)->GetDeliveryResult;
		
		switch ($delivery_status) {
		  case '0':
			$delivery_status = 'ارسال شده به مخابرات';
			break;
		  case '1':
			$delivery_status = 'رسیده به گوشی :D';
			break;
		  case '2':
			$delivery_status = 'نرسیده به گوشی';
			break;
		  case '3':
			$delivery_status = 'خطای مخابراتی';
			break;
		  case '5':
			$delivery_status = 'خطای نامشخص';
			break;
		  case '8':
			$delivery_status = 'رسیده به مخابرات';
			break;
		  case '16':
			$delivery_status = 'نرسیده به مخابرات';
			break;
		  case '100':
			$delivery_status = 'نامشخص';
			break;
		} 
		return $delivery_status;
	}
	
#####################
	if(isset($_POST['submit'])){
	
	$fetch_temp_query = "SELECT * FROM temp;";
	$fetch_temp_result = mysqli_query($connection,$fetch_temp_query);
	$fetch_temp_row = mysqli_fetch_assoc($fetch_temp_result);
	
	//$FromId = '100093995889';
	$FromId = $fetch_temp_row['temp_id'];
	
	$fetch_query="SELECT id,pan FROM transaction WHERE id > '$FromId' ; ";
	$fetch_result=mysqli_query($connection,$fetch_query);
	$test = array();	
		while($row = mysqli_fetch_assoc($fetch_result)){
			 $card_number = $row['pan'];
						$group_query="SELECT id,pan,amount FROM transaction WHERE id > '$FromId' AND pan = '$card_number' ; ";
						$group_result=mysqli_query($connection,$group_query);
						$sum = 0 ;
							while($group_row = mysqli_fetch_assoc($group_result)){		
								$sum = $group_row['amount'] + $sum;
							}														
							if(!in_array($row['pan'],$test)){
								$pan1 = substr($row['pan'],0,6);
								$pan2 = substr($row['pan'],12,4);
									$phone_query="SELECT mobile,first_name,last_name,gender FROM users WHERE 
													(cart_pri LIKE '$pan1%' AND cart_pri LIKE '%$pan2') OR
													(cart_sec LIKE '$pan1%' AND cart_sec LIKE '%$pan2')	OR 
													(cart_ter LIKE '$pan1%' AND cart_ter LIKE '%$pan2'); ";
									$phone_result=mysqli_query($connection,$phone_query);
									$phone_row = mysqli_fetch_assoc($phone_result);
								array_push($test,$row['pan']);
								echo $row['pan'].'='.$sum.','.$phone_row['mobile'].'<br>';
								$mobile = $phone_row['mobile'];
								$first_name = $phone_row['first_name'];
								$last_name = $phone_row['last_name'];
								$gender = $phone_row['gender'];
									if(isset($phone_row['mobile'])){
											if($gender=='مرد'){$smsgender='آقای';}elseif($gender=='زن'){$smsgender='خانم';}
										$message="$smsgender $first_name $last_name
										میزان سرمایه گذاری شده برای شما از خرید های دیروز : $sum ریال میباشد.
										www.scards.ir
												  ";
										pooya_sms($mobile,$message,$connection);
										echo '<font face="verdana" size="3" color="#009933">Done...!</font><br>';
									}
							}										
		}



	$temp_query = "SELECT id FROM transaction ORDER BY id DESC LIMIT 1;";
	$temp_result = mysqli_query($connection,$temp_query);
	$temp_row = mysqli_fetch_assoc($temp_result);
	$last_id = $temp_row['id'];
	
	$insert_temp_query = "UPDATE temp SET temp_id = '$last_id' WHERE id=1;";
	$insert_temp_result = mysqli_query($connection,$insert_temp_query);
	}
?>
<form method="post" role="form" class="form-inline">
	<input type="submit" name="submit" value="ارسال تمامی SMS ها" class="form-control btn btn-md btn-success">&nbsp;&nbsp;
تعداد اس ام اس باقیمانده : 
<?php
ini_set("soap.wsdl_cache_enabled", "0");
$getCredit = new SoapClient('http://87.107.121.54/post/Send.asmx?wsdl', array('encoding'=>'UTF-8'));

$getCreditParameters['username'] = "9124077897";
$getCreditParameters['password'] = "3755";

echo round($getCredit->GetCredit($getCreditParameters)->GetCreditResult);

?>
</form>
<br>
<?php
### TEST ###

									// test 
									//pooya_sms('09361946269','سلام',$connection);
								if(isset($_POST['get_delivery'])){
									$count = $_POST['count'];
									echo"
										<table class='table table-striped table-hover table-bordered'>
											<tr>
														<th>شماره موبایل</th>
														<th>متن پیام</th>
														<th>وضعیت ارسال</th>
														<th>تاریخ ارسال</th>
														<th>ارسال مجدد</th>
											</tr>
									";
									$get_delivery_query = "SELECT * FROM sms ORDER BY date DESC LIMIT $count;";
									$get_delivery_result = mysqli_query($connection,$get_delivery_query);

									while($get_delivery_row = mysqli_fetch_assoc($get_delivery_result)){
										
										$recId = pooya_delivery($get_delivery_row['recId']);
										$sms_date = jdate("Y/m/d - H:i:s",$get_delivery_row['date']);
										echo "
											  <tr>
														<td>$get_delivery_row[mobile]</td>
														<td>$get_delivery_row[text]</td>
														<td>$recId</td>
														<td>$sms_date</td>
														<td>
															<form method='post'  role='form' class='form-inline'>
																<input type='hidden' name='id' value='$get_delivery_row[id]'>
																<input type='submit' name='reSendSms' value='ارسال مجدد'  class='form-control btn btn-xs btn-warning'>
															</form>
														</td>		
											  </tr>";
										}
									echo"</table>";
								}
								
?>
<?php
	if(isset($_POST['reSendSms'])){
		$id = $_POST['id'];
		$re_send_sms_query = "SELECT * FROM sms WHERE id='$id';";
		$re_send_sms_result = mysqli_query($connection,$re_send_sms_query);
		$re_send_sms_row = mysqli_fetch_assoc($re_send_sms_result);
		pooya_sms($re_send_sms_row['mobile'],$re_send_sms_row['text'],$connection);
		}
?>
<form method="post" role="form" class="form-inline">
	<select name="count" class="form-control">
    	<option>10</option>
        <option>30</option>
        <option>50</option>
        <option>100</option>
        <option>200</option>
        <option value="1000000000">100 به بالا</option>
    </select>
	<input type="submit" name="get_delivery" value="گزارش تحویل"  class="form-control btn btn-md btn-primary">
</form>
<hr>
<?php


		
function pooya_sms_iterative($pooya_to,$pooya_message,$connection){
	
			$last_day = time() - (1 * 4 * 60 * 60);
		
			$iterative_query="SELECT * FROM sms WHERE mobile='$pooya_to' AND text='$pooya_message' AND date > $last_day ;";
			$iterative_result = mysqli_query($connection,$iterative_query);
			$iterative_row = mysqli_fetch_assoc($iterative_result);
			$count_sms = mysqli_num_rows($iterative_result);
			
				if($count_sms==0){
					ini_set("soap.wsdl_cache_enabled", "0");
					$sms_client = new SoapClient('http://87.107.121.54/post/send.asmx?wsdl', array('encoding'=>'UTF-8'));
					
					$parameters['username'] = "9124077897";
					$parameters['password'] = "3755";
					$parameters['to'] = $pooya_to;
					$parameters['from'] = "2188806627";
					$parameters['text'] =$pooya_message;
					$parameters['isflash'] =false;
					
					$recId = $sms_client->SendSimpleSMS2($parameters)->SendSimpleSMS2Result;
					$date = time();
						
					$mysqli = $connection;
			
					$send_sms_query = "INSERT INTO sms(`id`, `mobile`, `text`, `recId`, `date`) VALUES ('','$pooya_to','$pooya_message','$recId','$date')";
					$send_sms_result = mysqli_query($connection,$send_sms_query);
					return "$pooya_to $pooya_message فرستاده شد!";
				}else{
					return "به $pooya_to قبلا فرستاده شده است!";
					}
		
		}

if(isset($_POST['submit_iterative'])){
	
	$fetch_temp_query = "SELECT * FROM temp;";
	$fetch_temp_result = mysqli_query($connection,$fetch_temp_query);
	$fetch_temp_row = mysqli_fetch_assoc($fetch_temp_result);
	
	//$FromId = '100093995889';
	$FromId = $fetch_temp_row['temp_id'];
	
	$fetch_query="SELECT id,pan FROM transaction WHERE id > '$FromId' ; ";
	$fetch_result=mysqli_query($connection,$fetch_query);
	$test = array();	
		while($row = mysqli_fetch_assoc($fetch_result)){
			 $card_number = $row['pan'];
						$group_query="SELECT id,pan,amount FROM transaction WHERE id > '$FromId' AND pan = '$card_number' ; ";
						$group_result=mysqli_query($connection,$group_query);
						$sum = 0 ;
							while($group_row = mysqli_fetch_assoc($group_result)){		
								$sum = $group_row['amount'] + $sum;
							}														
							if(!in_array($row['pan'],$test)){
								$pan1 = substr($row['pan'],0,6);
								$pan2 = substr($row['pan'],12,4);
									$phone_query="SELECT mobile,first_name,last_name,gender FROM users WHERE 
													(cart_pri LIKE '$pan1%' AND cart_pri LIKE '%$pan2') OR
													(cart_sec LIKE '$pan1%' AND cart_sec LIKE '%$pan2')	OR 
													(cart_ter LIKE '$pan1%' AND cart_ter LIKE '%$pan2'); ";
									$phone_result=mysqli_query($connection,$phone_query);
									$phone_row = mysqli_fetch_assoc($phone_result);
								array_push($test,$row['pan']);
								echo $row['pan'].'='.$sum.','.$phone_row['mobile'].'<br>';
								$mobile = $phone_row['mobile'];
								$first_name = $phone_row['first_name'];
								$last_name = $phone_row['last_name'];
								$gender = $phone_row['gender'];
									if(isset($phone_row['mobile'])){
											if($gender=='مرد'){$smsgender='آقای';}elseif($gender=='زن'){$smsgender='خانم';}
										$message="$smsgender $first_name $last_name
										میزان سرمایه گذاری شده برای شما از خرید های دیروز : $sum ریال میباشد.
										www.scards.ir
												  ";
										echo pooya_sms_iterative($mobile,$message,$connection);
										//echo '<font face="verdana" size="3" color="#009933">Done...!</font><br>';
									}
							}										
		}



	$temp_query = "SELECT id FROM transaction ORDER BY id DESC LIMIT 1;";
	$temp_result = mysqli_query($connection,$temp_query);
	$temp_row = mysqli_fetch_assoc($temp_result);
	$last_id = $temp_row['id'];
	
	$insert_temp_query = "UPDATE temp SET temp_id = '$last_id' WHERE id=1;";
	$insert_temp_result = mysqli_query($connection,$insert_temp_query);
	}

?>

<form method="post" role="form" class="form-inline">
	<input type="submit" name="submit_iterative" value="ارسال پیشرفته" class="form-control btn btn-md btn-success">&nbsp;&nbsp;
</form>
</div>